query GetThreadPosts($thread: String) {
  GetThreadPosts(thread: $thread, order: { postedAt: DESC }) {
    id
    postedAt
    title
    attachmentUrl
    body
    score
    totalComment
    totalReply
    thread {
      id
      name
    }
    postedUser {
      name
      email
    }
  }
}
