query GetUserPostDetail($postId: String) {
  GetUserPostDetail(postId: $postId) {
    id
    title
    body
    attachmentUrl
    score
    totalComment
    totalReply
    postedAt
    totalPostVote
    postedUser {
      id
      name
      email
      description
      gender
      avatarUrl
    }
    thread {
      id
      name
      description
    }
    comments {
      id
      body
      parentId
      commentTime
      commentUser {
        id
        name
        description
        gender
        avatarUrl
      }
      inverseParent {
        id
        body
        parentId
        commentTime
        commentUser {
          id
          name
          description
          gender
          avatarUrl
        }
      }
    }
  }
}
